<?php

/**
 * PluginSidGroupeBandeauTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidGroupeBandeauTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSidGroupeBandeauTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidGroupeBandeau');
    }
}