<?php

/**
 * PluginSidBandeauTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidBandeauTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSidBandeauTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidBandeau');
    }
}