<?php

/**
 * PluginSidBandeau
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginSidBandeau extends BaseSidBandeau
{
public function show_groupe_select() {

        // on récupère l'id du groupe du bandeau
        $idGroupeBandeau = dmDb::table('SidGroupeBandeau')
                ->createQuery('a')
                ->leftJoin('a.SidBandeau b')
                ->where('b.id = ?',$this->id)
                ->fetchOne();
                return $idGroupeBandeau->title/*.sfContext::getInstance()->getId()*/;
        }
}