<?php

/**
 * PluginSidCabinetMissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidCabinetMissionTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSidCabinetMissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidCabinetMission');
    }
}