<?php

/**
 * PluginSidCabinetEquipeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidCabinetEquipeTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSidCabinetEquipeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidCabinetEquipe');
    }
}