<?php

/**
 * PluginSidCabinetMissionSidSectionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidCabinetMissionSidSectionTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSidCabinetMissionSidSectionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidCabinetMissionSidSection');
    }
}