<?php

/**
 * PluginSidCabinetEquipeSidRubriqueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidCabinetEquipeSidRubriqueTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginSidCabinetEquipeSidRubriqueTable The table object
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidCabinetEquipeSidRubrique');
    }
}