<?php

/**
 * PluginSidCabinetAccueilTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidCabinetAccueilTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSidCabinetAccueilTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidCabinetAccueil');
    }
}