<?php

/**
 * PluginSidCabinetMissionSidRubriqueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidCabinetMissionSidRubriqueTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginSidCabinetMissionSidRubriqueTable The table object
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidCabinetMissionSidRubrique');
    }
}