<?php

/**
 * PluginSidCabinetRecrutementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidCabinetRecrutementTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSidCabinetRecrutementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidCabinetRecrutement');
    }
}