<?php

/**
 * PluginSidCabinetEquipeSidSectionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidCabinetEquipeSidSectionTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSidCabinetEquipeSidSectionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidCabinetEquipeSidSection');
    }
}