<?php

/**
 * PluginSidCabinetPageCabinetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidCabinetPageCabinetTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSidCabinetPageCabinetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidCabinetPageCabinet');
    }
}