<?php

/**
 * PluginSidCabinetSelectionPlacementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidCabinetSelectionPlacementTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginSidCabinetSelectionPlacementTable The table object
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidCabinetSelectionPlacement');
    }
}