<?php

/**
 * PluginSidCabinetEquipe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginSidCabinetEquipe extends BaseSidCabinetEquipe
{
	public function infoEquipe(){
		return sfContext::getInstance()->getI18N()->__($this->title).' '.$this->name.' '.$this->first_name.' - '.$this->statut;
	}
}