#!/usr/bin/env php
<?php

if (!defined('STDIN'))
{
  die("\n L\installeur doit etre execute en ligne de commande.\n");
}

/*
if (is_dir(getcwd().'/dmCorePlugin'))
{
  die("\n /!\ Vous devez creer un nouveau site dans un dossier vide /!\ \n \n");
}
*/

$projectName = basename(getcwd());

// test si dossier vide
$dir = getcwd();
if (is_dir($dir)) {
    if ($Pointeur = opendir($dir)) {
        while (($file = readdir($Pointeur)) !== false) {
            if ($file != "." && $file != ".." && $file != "core") {
                die("\n Le dossier n'est pas vide. Seul un dossier nommé 'core' peut être accepté.\n");
            }
        }
        closedir($Pointeur);
    }
}

//
//if (PHP_OS == 'Linux') {
    // création dossiers
//    mkdir('htdocs', 0755);
//    mkdir('logs', 0755);
    mkdir('conf', 0755);
//    mkdir('data', 0755);  
    // changement dossier courant
    //chdir('htdocs');
    $installer = dirname(__FILE__).'/dmCorePlugin/config/installer.php';
//} else {
//    $installer = dirname(__FILE__).'/dmCorePlugin/config/installer-windows.php';
//}


$_SERVER['argv'] = array(
  $_SERVER['argv'][0],
  'generate:project',
  $projectName,
  '--installer='.$installer  
);

//var_dump($_SERVER['argv']);

require_once dirname(__FILE__).'/symfony/lib/command/cli.php';

return 0;