<?php

/**
 * PluginSidRubrique
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginSidRubrique extends BaseSidRubrique
{
        public function show_list_rubrique_without_agenda() {

            $nameRubrique = dmDb::table('SidRubrique')->findOneByTitle('agenda');
        
            
          if($this->id != $nameRubrique->id){  
        // on récupère le name de la page de la rubrique, plutot que le title de la rubrique, ou section...
        $rubriquePage = dmDb::table('DmPage') //->findAllBySectionId($vars['section']);
                ->createQuery('p')
                ->where('p.module = ? and action=? and record_id=?', array('rubrique', 'show', $this->id))
                ->limit(1)
                ->execute();
        
        return $rubriquePage[0]->name ;
          }
          else return false;
    }
    
    public function show_list_rubrique() {

           
        // on récupère le name de la page de la rubrique, plutot que le title de la rubrique, ou section...
        $rubriquePage = dmDb::table('DmPage') //->findAllBySectionId($vars['section']);
                ->createQuery('p')
                ->where('p.module = ? and action=? and record_id=?', array('rubrique', 'show', $this->id))
                ->limit(1)
                ->execute();
        
        return $rubriquePage[0]->name ;
        
        }

}