<?php

/**
 * PluginSidCreationRubriqueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidCreationRubriqueTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginSidCreationRubriqueTable The table object
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidCreationRubrique');
    }
}