<?php

/**
 * PluginSidSectionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidSectionTable extends myDoctrineTable {

    /**
     * Returns an instance of this class.
     *
     * @return object PluginSidSectionTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('PluginSidSection');
    }

/**
 *
 * @param <type> $title
 * @param <type> $idRubrique
 * @return SidSection 
 */
    public function getSectionByTitleAndRubriqueId($title, $idRubrique) {
        $a = $this->createQuery('c')
                        ->leftJoin('c.Translation rt')
                        ->where('rt.title = ? and is_active = ? and rubrique_id = ?', array($title, true, $idRubrique));

        if ($a->execute()->count() == 0) {
            return new SidSection();
        } else {
            return $a->fetchOne();
        }
    }
    
    public function findOneByTitleAndIsActiveAndRubriqueId($title, $rubriqueId) {
        $a = $this->createQuery('s')
                ->leftJoin('s.Translation st')
                ->where('st.title = ? and is_active = ? and rubrique_id = ?', array($title, true, $rubriqueId));

        if ($a->execute()->count() < 1) {
            $section = new SidSection();
            return $section;
        } else {
            return $a->fetchOne();
        }
    }
    
    public function findOneByTitleAndRubriqueId($title, $rubriqueId) {
        $a = $this->createQuery('s')
                ->leftJoin('s.Translation st')
                ->where('st.title = ? and rubrique_id = ?', array($title, $rubriqueId));

        if ($a->execute()->count() < 1) {
            $section = new SidSection();
            return $section;
        } else {
            return $a->fetchOne();
        }
    }

}