default:

  i18n:
    catalogue:            dm
    form:                 merge                     # Can be merge or embed

  html:
    doctype:
      name:               html                      # Doctype ( 'html', 'xhtml' )
      version:            5                         # Doctype xhtml version ( '1.0', '1.1' ) or html version ( '4', '5' )

  toolBar:
    enabled:              true

  pageBar:
    enabled:              true

  mediaBar:
    enabled:              true

  admin:
    max_per_page:         [ 3, 5, 10, 15, 20, 30, 50, 100, ∞ ]  # admin lists paginators
    list_truncate:        120                                   # truncate big descriptions in admin lists

  console:                                                      # emulate a linux shell
                                                                # commands available
    commands:            'sf ls ccc css css-sprite infos'       #'sf man ll ls pwd cat mkdir rm cp mv touch chmod free df find clear php'
    aliases:                                                    # aliases available
      'ls':
        command:         'ls -la'
        description:     'List files and directory'
      'ccc':
        command:         'sf ccc'
        description:     'Clear cache'
      'css':
        command:         'sf less:compile-all'
        description:     'Compile the .less files into .css files'
      'css-sprite':
        command:         'sf less:sprite'
        description:     'Generate sprites (Graphic V1 only)'
      'infos':
        command:         'sf dm:infos-site'
        description:     'Site infos'

  service:                                                      # Dependency Injection Container configuration
    container_base_class: dmAdminBaseServiceContainer           # The service container base class

  # Les liens rapides 
  express:     
    links:
      "Home":                    "/admin.php"
#      "Sitemap":                "/admin.php/seo/sitemap/manage-xml-sitemap/index"
#      "Search index":           "/admin.php/tools/search-engine/manage-index/index"
      "Console":                 "/admin.php/system/dev/diem-console/index"
      "Configuration":           "http://sitediem.com/admin.php/tools/configuration/configuration-panel/index"
      "Constants":               "/admin.php/tools/configuration/constantes/index"
      "Media":                   "/admin.php/tools/media/media/path"
      "Google Analytics":        "/admin.php/seo/services/google-analytics/index"
      "SEO management":          "/admin.php/seo/pages/automatic-seo"