<?php

/**
 * PluginSidContactFormTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidContactFormTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginSidContactFormTable The table object
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidContactForm');
    }
}