<?php

/**
 * PluginSidContactDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidContactDataTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginSidContactDataTable The table object
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidContactData');
    }
}