<?php

/**
 * PluginSidContactFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidContactFieldTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginSidContactFieldTable The table object
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidContactField');
    }
}