<?php

/**
 * PluginSidActuArticleSidRubriqueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidActuArticleSidRubriqueTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginSidActuArticleSidRubriqueTable The table object
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidActuArticleSidRubrique');
    }
}