<?php

/**
 * PluginSidActuTypeArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidActuTypeArticleTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSidActuTypeArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidActuTypeArticle');
    }
}