<?php

/**
 * PluginSidActuTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidActuTypeTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSidActuTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidActuType');
    }
}