<?php

/**
 * PluginSidActuArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidActuArticleTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSidActuArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidActuArticle');
    }
}