<?php
echo
$form->renderGlobalErrors(),
 _tag('div', 
		 $form['facebook']->renderRow().
		 $form['googleplus']->renderRow().
		 $form['linkedin']->renderRow().
		 $form['twitter']->renderRow().
		 $form['viadeo']->renderRow().
		 $form['vimeo']->renderRow().
		 $form['cssClass']->renderRow()
);