<?php

/**
 * PluginSidAddedPagesLevel3Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidAddedPagesLevel3Table extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginSidAddedPagesLevel3Table The table object
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidAddedPagesLevel3');
    }
}