<?php

/**
 * PluginSidAddedPagesGroupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidAddedPagesGroupsTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginSidAddedPagesGroupsTable The table object
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidAddedPagesGroups');
    }
}