<?php

/**
 * PluginSidAddedPagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidAddedPagesTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginSidAddedPagesTable The table object
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidAddedPages');
    }
}