<?php

/**
 * PluginSidAddedPagesLevel1Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidAddedPagesLevel1Table extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginSidAddedPagesLevel1Table The table object
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidAddedPagesLevel1');
    }
}