<?php

/**
 * PluginSidAddedPagesLevel2Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidAddedPagesLevel2Table extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginSidAddedPagesLevel2Table The table object
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidAddedPagesLevel2');
    }
}