<?php

/**
 * PluginSidCoordName
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginSidCoordName extends BaseSidCoordName
{
public function show_list_ville() {

        // on récupère le nom de la ville
        

        $ville = $this->getVille();

        return $ville;
        
    }

public function cabinet_ville() {

        // on récupère le nom du cabinet - la ville (siège social) si tel est le cas
        
        $cabinet = $this->getTitle();
        $ville = $this->getVille();
        ($this->siege_social == true) ? $siege = ' (siège social)' : $siege = '';
        return $cabinet.' à '.$ville.$siege;
        
    }
}