<?php

/**
 * PluginSidCoordNameTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidCoordNameTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSidCoordNameTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidCoordName');
    }
}