<?php

/**
 * PluginSidGroupeSitesUtilesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidGroupeSitesUtilesTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSidGroupeSitesUtilesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidGroupeSitesUtiles');
    }
}