<?php

/**
 * PluginSidSitesUtilesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidSitesUtilesTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSidSitesUtilesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidSitesUtiles');
    }
}