<?php

/**
 * PluginSidIndexSitesUtilesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidIndexSitesUtilesTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSidIndexSitesUtilesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidIndexSitesUtiles');
    }
}