all:
  .settings:
    #Gestion des différents CDN
    js_cdn_google:					//ajax.googleapis.com/ajax/libs
    js_cdn_cdnjs:						//cdnjs.cloudflare.com/ajax/libs
    #Chemin vers les différentes partie du framework
    js_path_framework:			/theme/less/_framework/SPLessCss/Externals/js