# default values
all:
  dm-media:
    max-upload-size: 1000000   # Max upload size for file in form

  link-login:      # seeclass BasedmUserAdminActions to understand how it works
    active:  true   # activation du lien de login
    user: client
    ips-allowed:    # ips allowed to call autologin func in site. Complete or incomplete IP's accepted. WARNING: The parameter "268.235.247." give acces to all ip's begin by, like "268.235.247.1", "268.235.247.2" etc...
      - 127.0.0.1
      - 91.194.100.238  # IP of EA 
      - 91.194.100.242  # IP of EA SSL
  email:
    default-sender: "votreconseil@expertinfos.com"

  controllers-access:    # param for controller's (dev.php, less.php) access
    ips-allowed:   # complete or incomplete IP's accepted. WARNING: The parameter "268.235.247." give access to all ip's begin by, like "268.235.247.1", "268.235.247.2" etc...
      - 127.0.0.1
      - 217.108.240.193
      - 217.108.240.209
      - 217.108.240.217
      - 217.108.240.225
      - 192.168.81.220
      - 89.89.143.127     # Ip fixe Seb Rocca      
      - 192.168.81.220    # Ip SIDPresse réseau local de Arnaud
      - 192.168.81.127    # Ip SIDPresse réseau local de Gilles
      - 192.168.81.132    # IP SIDPresse réseau local de l'iPad
      - 88.175.117.82     # Ip fixe Marie Laure Nauleau 
      - 93.10.138.101     # Ip fluctuante d'Alicia
      - 217.128.36.230    # Ip fixe co-pilotes
    ips-message:                       # message display on admin.php if client's ip is not allowed (in list above)
      "91.194.100.239": "Afin de vous connecter merci de vous rendre dans votre <a href=\"http://abonnes.expert-infos.com\">espace abonné</a>."  # ip of server which run sites      

  #variable utilisées dans les différents partials du site
  vars-partial:
    separator: '&#160;:&#160;'
    dash: '&#160;-&#160;'
    ellipsis: '&#160;(...)'
    #longueur de texte de description par défaut
    defaultValueLength: 200

  # traductions des noms des modules en fonction du type de site
  traductions-module:     
    # changement des noms des rubriques en fonction du client_type (ec ou cgp)
    # ancien : nouveau
    cgp-fr:
      "Les missions": Les services
      "Les Missions": Les Services
      "Description des missions": Description des services
      "Mission|Les Missions": Service|Les Services
      "Présentation du Cabinet": Présentation
      "L'Actualité du Cabinet|Les Actualités du Cabinet": "Notre Actualité|Nos Actualités"
      "Actualité du Cabinet": "Notre Actualité"

    aga-fr:
      "Le cabinet": "L'Association"
      "Les missions": Les prestations
      "Les Missions": Les Prestations
      "Description des missions": Description des prestations
      "Mission|Les Missions": Prestation|Les Prestations
      "Description du Cabinet": "Description de l'association"
      "Présentation du Cabinet": "Présentation de l'Association"
      "Le Cabinet": "L'Association"
      "L'Actualité du Cabinet|Les Actualités du Cabinet": "Notre Actualité|Nos Actualités"
      "Actualité du Cabinet": "Actualités de l'association"

    copilotes-fr:

  # tableau des description des permissions 
  permissions:
    list:
      # Autorisations particulières sans rapport avec le menu de l'Admin
      system: "Accès au Système d'Administration"
      ck_editor_lite: ckEditor Lite
      ck_editor_co_pilotes: ckEditor Co-pilotes
      admin_bandeau_lite: 'Administration du bandeau Lite'
      super_admin: 'Acces super Admin'
      admin: "Admin => Accès au compte de l'administrateur"
      loremize: "Admin => Création de contenu aléatoire (pour Test)"
      page_bar_admin: "Admin => Affichage de la barre d'outil PAGE"
      media_bar_admin: "Admin => Affichage de la barre d'outil MEDIA "
      tool_bar_admin: "Admin => Affiche la barre supérieure des menus déroulant"
      see_accueil: "Menu général remis en forme"
      # Menu Contenu
      #
        # Sous-menu Retours visiteur
      contact_me: "Contenu => Retour visiteur => Contacts (messages via le formulaire de contact)"
        # Sous-menu Base Editoriale
      rubrique: "Contenu => Base Editoriale => Rubriques (Gestion des rubriques de la BE)"
      section: "Contenu => Base Editoriale => Sections (Gestion des sections de la BE)"
      article: "Contenu => Base Editoriale => Articles (Gestion des articles de la BE)"
        # Sous-menu Page additionnelles
      added_page: "Contenu => Pages Additionnelles"
        # Sous-menu Tag
      tags: "Contenu => Tag => Tags (Gestion des tags)"
      # Menu Gestion du bandeau
      # 
        # Sous-menu Bandeau défilant
      groupe_bandeau: "Gestion du bandeau => Bandeau défilant => Mes groupes de bandeau"
      bandeau: "Gestion du bandeau => Bandeau défilant => Mes Bandeaux"
      # Menu Le cabinet
      # 
        # Sous-menu Description du cabinet
      page_cabinet: "Le cabinet => Description du cabinet => Les pages du cabinet"
      equipe: "Le cabinet => Description du cabinet => Equipes"
      recrutement: "Le cabinet => Description du cabinet => Recrutements"
      selection_placement: "Le cabinet => Description du cabinet => Selection de placement (CGP)"
        # Sous-menu Actualité du cabinet
      type_actu: "Le cabinet => Actualité du cabinet => Type de mes articles"
      actualite_contenu: "Le cabinet => Actualité du cabinet => Actualités du cabinet"
        # Sous-menu Mes Coordonnées
      renseignements: "Le cabinet => Mes Coordonnées => Renseignements"
        # Sous-menu Mes sites utiles
      index_sites_utiles: "Le cabinet => Mes sites utiles => Page d'accueil des sites utiles"
      groupe_sites_utiles: 'Le cabinet => Mes sites utiles => Les groupes de sites utiles'
      sites_utiles: "Le cabinet => Mes sites utiles => Les sites utiles"
      # Menu Les Missions
      # 
        # Sous-menu Description des missions
      mission: "Les Missions => Description des missions"
      # Menu Référencement
      # 
        # Sous-menu Services
      use_google_analytics: "Référencement => Services =>  Google Analytics"
      google_analytics: "Référencement => Services =>  Google Analyticss"
      use_google_webmaster_tools: "Référencement => Services =>  Google Webmaster Tools"
      google_webmaster_tools: "Référencement => Services =>  Google Webmaster Tools"
        # Sous-menu Sitemap
      sitemap: "Référencement => Sitemap => Gérer le sitemap XML"
        # Sous-menu Pages
      manual_metas: "Référencement => Pages =>  Gérer les pages (Gérer les métas)"
      manage_pages: "Référencement => Pages =>  Gérer les pages (Réordonner les pages)"
      automatic_metas: "Référencement => Pages =>  Référencement automatique (Gérer les métas)"
        # Sous-menu Redirections
      url_redirection: "Référencement => Redirections =>  Redirections d'urls"
      # Menu Système
      # 
        # Sous-menu Configuration
      configuration: "Système => Configuration => Paramètres"
        # Sous-menu Journal
      sent_mail: "Système => Journal => Courriels envoyés"
      error_log: "Système => Journal => Erreurs (voir les mails en erreur)"
        # Sous-menu Dev
      see_diagrams: "Système => Dev => Voir les schémas ( Graphique du modèle de données)"
      code_editor: "Système => Dev => Editeur de code (Accès aux codes du site)"
      diem_console: "Système => Dev => Console Diem (Accès console)"
      see_server: "Système => Dev => Serveur (Config sur serveur)"
        # Sous-menu Sécurité
      security_user: "Système => Sécurité =>Utilisateurs (Gestion des droits des utilisateurs coté Admin)"
      security_permission: "Système => Sécurité => Autorisations (Gestion des Autorisations coté Admin)"
      security_group: "Système => Sécurité => Groupes (Gestion des Autorisations classées par Groupe)"
      security_record: "Système => Sécurité => Permissions sur les Enregistrements"
      security_record_permission_association: "Système => Sécurité => Associations sur les Permissions d'Enregistrements"
      # Menu Outils
      # 
        # Sous-menu Configuration 
      config_panel: "Outils => Configuration => Panneau de configuration"
      mail_template: 'Outils => Configuration => Gabarits des courriels (Gestion des messages types)'
      layout: "Outils => Configuration => Layouts (Gérer les Layouts du site)"
      constantes: "Outils => Configuration => Gestion des constantes du site"
        # Sous-menu Traduction 
      translation: "Outils => Traduction => Phrases (Gestion des phrases à traduire)"
      catalogue_translation: "Outils => Traduction => Catalogues (Gestion des catalogues des phrases de traductions)"
        # Sous-menu Surveillance 
      see_chart: "Outils => Surveillance => Graphique (Historique des visite)"
      see_log: "Outils => Surveillance => Journal (Listing de Logs)"
        # Sous-menu Média 
      media_library: "Outils => Média => Média (Gérer les médias depuis l'Admin)"
        # Sous-menu Moteur de Recherche 
      search_engine: "Outils => Moteur de Recherche => Gérer l'index"
      # Menu BOT
      # 
        # Sous-menu Internal Bot 
      bot: "Outils => BOT => Internal Bot (Contrôle de la vitesse de chargement des pages)"
      #  
      # Divers autorisations pour la gestion des widgets coté front
      zone_add: "Coté Front => Add zones"
      zone_edit: "Coté Front => Edit zones"
      zone_delete: "Coté Front => Delete zones"
      widget_add: "Coté Front => Add widgets"
      widget_edit: "Coté Front => Edit widgets"
      widget_delete: "Coté Front => Delete widgets"
      widget_edit_fast: 'Coté Front => Can fast edit widgets'
      widget_edit_fast_record: 'Coté Front => Fast edit widget record'
      widget_edit_fast_content_title: 'Coté Front => Fast edit widget content title'
      widget_edit_fast_content_link: 'Coté Front => Fast edit widget content link'
      widget_edit_fast_content_image: 'Coté Front => Fast edit widget content image'
      widget_edit_fast_content_text: 'Coté Front => Fast edit widget content text'
      widget_edit_fast_navigation_menu: 'Coté Front => Fast edit widget navigation menu'
      page_add: "Coté Front => Add pages"
      page_edit: "Coté Front => Edit pages"
      page_delete: "Coté Front => Delete pages"
      page_bar_front: "Coté Front => See page bar in front"
      media_bar_front: "Coté Front => See media bar in front"
      tool_bar_front: "Coté Front => See toolbar in front"
      # Divers - A voir
      clear_cache: "Clear the cache"
      log: "Manage logs"
      content: "CRUD dynamic content in admin"
      site_view: "See non-public website and inactive pages"
      media_ignore_whitelist: "Upload media with any filetype"
      export_table: "Export table contents"
      xiti: "Configure Xiti"
      see_request: 'See the requests window'
      see_event: 'See the events window'
      interface_settings: 'Manage interface settings like default image resize method'

  groupes-permissions-client-web:
    description: "Accès pour le client Web"
    permissions:
      - bandeau
      - see_accueil
#      - see_log
      - see_chart
      - tool_bar_admin
      - admin
      - ck_editor_lite
      - admin_bandeau_lite
      - sites_utiles
      - groupe_sites_utiles
      - index_sites_utiles
      - page_cabinet
      - equipe
      - recrutement
      - mission
      - actualite_contenu
      - contact_me

  groupes-permissions-client-web-co-pilotes:
    description: "Accès pour le client Web - Co-pilotes"
    permissions:
      - bandeau
      - see_accueil
#      - see_log
      - see_chart
      - tool_bar_admin
      - admin
      - ck_editor_lite
      - admin_bandeau_lite
      - sites_utiles
      - groupe_sites_utiles
      - index_sites_utiles
      - equipe
      - recrutement
      - contact_me
      - added_page

  groupes-permissions-co-pilotes:
    description: "Accès pour co-pilotes"
    permissions:
      - bandeau
      - see_accueil
#      - see_log
      - see_chart
      - tool_bar_admin
      - admin
      - admin_bandeau_lite
      - sites_utiles
      - groupe_sites_utiles
      - index_sites_utiles
      - equipe
      - recrutement
      - contact_me
      - ck_editor_co_pilotes
      - page_bar_admin
      - media_bar_admin
      - tool_bar_admin
      - widget_add
      - widget_edit
      - widget_delete
      - widget_edit_fast
      - widget_edit_fast_record
      - widget_edit_fast_content_text
      - widget_edit_fast_navigation_menu
      - page_add
      - page_edit
      - page_delete
      - page_bar_front
      - media_bar_front
      - tool_bar_front
      - added_page
      - media_library

  groupes-permissions-base-doc:
    description: "Accès pour le client Base Doc"
    permissions:
      - see_accueil
      - see_chart
      - tool_bar_admin
      - admin

  # Filtrage d'affichage de certains widgets (exemple: quand admin-co-pilotes se log sur le front)   
  filtre-affichage-widget-module-action:
    co-pilotes:  # le nom du usergroup 
      - dmWidgetContent-title
      - dmWidgetContent-link
      - dmWidgetContent-text
      - dmWidgetContent-image
      - dmWidgetContent-imagePlus
      - dmWidgetContent-nivoGallery
      - dmWidgetContent-ckEditor
      - dmWidgetContent-gallery
      - dmWidgetContent-flowPlayer
      - dmWidgetContent-galleryBackground

  modules-specifiques:
    cgp-site:
      - selection_placement
    cgp-base-doc:
    ec-site:
    ec-base-doc:
    aga-site:
    aga-base-doc:
    copilotes-site:
#      - selection_placement

  # tableau pour gérer les pages à afficher dans le sitemap
  pages-for-sitemap:     
    # array[key] is a name of the page
    not-visibles:
      #array[key] is module
      #array[value] is action
      article:
        "article": show
      404:
        "main": error404
      search:
        "main": search
      signin:
        "main": signin
        
  
