# default values
all:
  link-login:    
    active:  true   # activation du lien de login
    user: client
    hashkey: 154774875454
    ips-allowed:    # complete or incomplete IP's accepted. WARNING: The parameter "268.235.247." give acces to all ip's begin by, like "268.235.247.1", "268.235.247.2" etc...
      - 127.0.0.1

  controllers-access:    # param for controller's (dev.php, less.php) access
    ips-allowed:   # complete or incomplete IP's accepted. WARNING: The parameter "268.235.247." give acces to all ip's begin by, like "268.235.247.1", "268.235.247.2" etc...
      - 127.0.0.1
      - 217.108.240.193
      - 217.108.240.209
      - 217.108.240.217
      - 217.108.240.225
      - 192.168.81.220

  #variable utilisées dans les différents partials du site
  vars-partial:
    separator: '&#160;:&#160;'
    dash: '&#160;-&#160;'
    ellipsis: '&#160;(...)'
    #longueur de texte de description par défaut
    defaultValueLength: 200

