all:
  .settings:
    enabled_modules:
      - dmWidgetGoogleMap
      - sidActuArticle
      - sidActuArticleAdmin
      - sidActuRubrique
      - sidActuRubriqueAdmin
      - sidActuTypeContenu
      - sidActuTypeContenuAdmin
      - accueil
      - accueilAdmin
#      - equipe
      - equipeAdmin
      - mission
      - missionAdmin
      - pageCabinet
      - pageCabinetAdmin
      - recrutement
      - recrutementAdmin
      - renseignements
      - renseignementsAdmin
      - sitesUtiles
      - groupeSitesUtiles
      - indexSitesUtiles      
      - sitesUtilesAdmin
      - groupeSitesUtilesAdmin
      - indexSitesUtilesAdmin
#      - groupeBandeau      
      - groupeBandeauAdmin
      - constantes
      - constantesAdmin
      - sidBlogArticle
      - sidBlogArticleAdmin
      - sidBlogTypeContenu
      - sidBlogTypeContenuAdmin
      - sidBlogRubrique
      - sidBlogRubriqueAdmin
      - bandeau
      - bandeauAdmin
      - dmWidgetNivoGallery
      - dmTagAdmin
      - dmTag
      - section
      - sectionAdmin
      - rubrique
      - article
      - rubriqueAdmin
      - articleAdmin
      - dmCkEditor
      - dmContact
      - dmContactAdmin
      - dmBotAdmin
      - dmMediaUploadifyerAdmin
      - dmWidgetFeedReader
      - dmWidgetExcel
      - dmWidgetGallery
      - sfLESS
      - dmWidgetXml
      - dmFlowPlayer
      - dmWidgetExternalVideo
      - dmCoreTranslator
      - sidWebservices
      - debug
      - vacpicpdd  # webservices
      - acs
      - cce
      - cd
      - cjo
      - cl
      - cld
      - ct
      - ctr
      - cvp
      - fk
      - hs
      - srtb
      - trc
      - trsvc
      - va
      - vasvc
      - vt
      - selectionPlacement
      - selectionPlacementAdmin
      - rubriqueCreation