all:
  .settings:
    enabled_modules:
      - dmWidgetGoogleMap
      - sidActuArticle
      - sidActuArticleAdmin
      - sidActuRubrique
      - sidActuRubriqueAdmin
      - sidActuTypeContenu
      - sidActuTypeContenuAdmin
      - accueil
      - accueilAdmin
#      - equipe
      - equipeAdmin
      - mission
      - missionAdmin
      - pageCabinet
      - pageCabinetAdmin
      - recrutement
      - recrutementAdmin
      - renseignements
      - renseignementsAdmin
      - sitesUtiles
      - groupeSitesUtiles
      - indexSitesUtiles      
      - sitesUtilesAdmin
      - groupeSitesUtilesAdmin
      - indexSitesUtilesAdmin
#      - groupeBandeau      
      - groupeBandeauAdmin
      - constantes
      - constantesAdmin
      - sidBlogArticle
      - sidBlogArticleAdmin
      - sidBlogTypeContenu
      - sidBlogTypeContenuAdmin
      - sidBlogRubrique
      - sidBlogRubriqueAdmin
      - bandeau
      - bandeauAdmin
      - dmWidgetNivoGallery
      - dmTagAdmin
      - dmTag
      - section
      - sectionAdmin
      - rubrique
      - article
      - rubriqueAdmin
      - articleAdmin
      - dmCkEditor
      - dmContactMe
      - dmContactMeAdmin
      - dmBotAdmin
      - dmMediaUploadifyerAdmin
      - dmWidgetFeedReader
      - dmWidgetExcel
      - dmWidgetGallery
      - sfLESS
      - dmWidgetXml
      - dmFlowPlayer
      - dmWidgetExternalVideo
      - dmCoreTranslator
      - sidSPLessCss
      - sidWebservices