<?php

/**
 * PluginDmContactMeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmContactMeTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmContactMeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmContactMe');
    }
}