js:

  front:
    ctrl:             dmFrontCtrl
    editCtrl:         dmFrontEditCtrl
    form:             dmFrontForm
    toolBar:          dmFrontToolBar
    pageBar:          dmFrontPageBar
    mediaBar:         dmFrontMediaBar
    codeEditor:       dmFrontCodeEditor
    page:             page/dmPage
    area:             page/dmArea
    zone:             page/dmZone
    widget:           page/dmWidget
    widgetForms:      widgetForm/dmWidgetForms
    widgetMenuForm:   widgetForm/dmWidgetNavigationMenuForm
    pageEditForm:     dmFrontPageEditForm
    pageAddForm:      dmFrontPageAddForm
    ajaxPager:        dmFrontAjaxPager

css:

  front:
    base:             base
    dmReset:          dmReset
    toolBar:          toolBar
    pageBar:          pageBar
    mediaBar:         mediaBar
    form:             form
    zone:             zone
    widget:           widget
    codeEditor:       codeEditor
    pageEditForm:     pageEditForm
    widgetMenuForm:   widgetForm/menu
    dmWidget:					/theme/css/_templates/BaseTheme/Widgets/NavigationMenu/NavigationMenu.css
    #ajout des CSS du framework css personnalisé menu:							<?php echo sfConfig::get('css_path_template') ?>/NavigationMenu/NavigationMenu.css
    