<?php

/**
 * PluginSidActuArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginSidActuArticle extends BaseSidActuArticle
{
     /**
     *
     * @return string section's page's name of the article
     * 
     */
    public function getActuRubriquePageName() {
        $actuRubrique = dmDb::table('DmPage')
                ->createQuery('p')
                ->where('p.module = ? and action=? and record_id=?', array('sidActuRubrique', 'show', $this->getRubrique()->id))
                ->limit(1)
                ->execute();
        return $actuRubrique[0]->name;
    }
    

}