<?php

/**
 * PluginSidActuRubriqueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidActuRubriqueTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSidActuRubriqueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidActuRubrique');
    }
}