<?php

/**
 * PluginSidActuArticleSidSectionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidActuArticleSidSectionTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSidActuArticleSidSectionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidActuArticleSidSection');
    }
}