<?php

/**
 * PluginSidBlogRubriqueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidBlogRubriqueTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSidBlogRubriqueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidBlogRubrique');
    }
}