<?php

/**
 * PluginSidBlogArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidBlogArticleTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSidBlogArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidBlogArticle');
    }
}