<?php

/**
 * PluginSidBlogTypeArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidBlogTypeArticleTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSidBlogTypeArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidBlogTypeArticle');
    }
}