<?php

/**
 * PluginSidBlogTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSidBlogTypeTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSidBlogTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSidBlogType');
    }
}